### ISSUE TITLE
Server reporting bad replays

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/server#102]
Server is reporting live games in the Online Vault tab, which cause an exception when you try to load them in the client.

See: https://github.com/FAForever/client/issues/270

**Comment by Sheeo** [comment]
Problem isn't that it's reporting live games, but that it's reporting games that have corrupted replays. For now we don't have an easy way of figuring out whether a replay is corrupt or not.

**Comment by HardlySoftly** [comment]
Its reporting games that are still in progress, and when the client requests them it sends back an empty object (which is what is giving off all the errors)

**Comment by Askaholic** [comment]
Replays are handled by the API
