### ISSUE TITLE
Make sure games are ranked if an ACU was killed by the enemy team

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#109]
The early unrankedness feature is there to prevent early disconnects from affecting games and allowing players to opt out of rankedness in such cases.

This shouldn't apply to early rush strategies, so we must make sure to rank these games in all circumstances.

**Comment by Brutus5000** [comment]
I would hook into the GameStatsService and inform the game about whethere ACUs haven been killed or not. Question: If a player leaves the game, his ACU is destroyed. Will this show up in the GameService as killed ACU?

**Comment by Brutus5000** [comment]
My new proposal is here: https://github.com/FAForever/fa/pull/1323

**Comment by aeoncleanse** [comment]
Game side merged as 44349849ce6340182c5d6d9dd0413179b53dd0c9

**Comment by Brutus5000** [comment]
Server side was merged as well. (Connects to #143).
This issue can be closed.
