### ISSUE TITLE
Provide time zone for players

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#113]
The server should read a user's time-zone from the login message, store it in the database and provide it as player info.

This way that clients can display a user's local time.
## Acceptance criteria
- If a client reports a time zone, the server stores it in the DB
- Missing time zone in login message does not have any effect
- The time zone is sent to clients as player_info in both, initial and increment player lists
- If a time zone is not set for a player, the time zone is either not included in the message or `null`

**Comment by Askaholic** [comment]
Closing, as we have no plans to implement this
