### ISSUE TITLE
Rating bug due to trueskill ratinggroup / ranks data mismatch

### ISSUE THREAD

**Issue by Crotalus** [FAForever/server#122]
https://github.com/FAForever/server/blob/develop/server/games/game.py#L624

The team sorting are messing up the data for the trueskill rate() function, the ranks key order is no longer guaranteed to match the corrensponding ratinggroup key

So the actual team number change the outcome of the rating, in a 1v1 you will get reversed result if someone is Team 3 instead of 2

**Comment by Crotalus** [comment]
Nvm, actually simulated running the current code and that seems an non-issue :/

**Comment by Sheeo** [comment]
The code is still rather convoluted for my taste though. Would like for a restructuring of it to make it much clearer what's going on when you read it :)
