### ISSUE TITLE
Revise server protocol

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#124]
Have a look at https://github.com/FAForever/server/wiki/Server-protocol-discussion

Most points have already been implemented or become obsolete.

The goal of this issue is to implement everything that makes sense and discard what doesn't, so that this wiki page can be deleted.
### Acceptance criteria
- Every point in the wiki page has either been implemeted or decided against
- The wiki page has been deleted

**Comment by Askaholic** [comment]
See #573
