### ISSUE TITLE
Rating decay

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#125]
Would it make sense to decay ratings over time? Imagine Zock never ever plays ladder again; as far as I understand, it's almost (or actually) impossible to rank higher than him.

Or is this handled enough by the "active" flag? If so, would we want the same for custom rating?

**Comment by Sheeo** [comment]
See this thread on the forums: http://forums.faforever.com/viewtopic.php?f=42&t=11025

My opinion: Yes, we need rating decay -- the 'active' flag on the database needs to go.

**Comment by micheljung** [comment]
Thx #129
