### ISSUE TITLE
Omit UID check for "trusted users"

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#128]
In order for developers and automated system tests to log in with multipler users or from virtual machines, users should have a `trusted` flag that causes the UID check to be omitted.

### Acceptance criteria
* `trusted` flag in the login table, not set for all except test users
* UID check *does* fire on login for users with flag not set
* UID check **does not** fire on login for users with flag set

**Comment by Sheeo** [comment]
We have this feature, entries in this table: https://github.com/FAForever/db/blob/develop/db-structure.sql#L1189 bypass the uniqueid system.

The users in this table are fetched at interval from the playerservice: https://github.com/FAForever/server/blob/develop/server/player_service.py#L127
