### ISSUE TITLE
Implement rating decay

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#129]
To be described
- Rating decay
- Remove "inactive" flag

**Comment by JaggedAppliance** [comment]
http://forums.faforever.com/viewtopic.php?f=42&t=11025&start=20#p113341
I think we don't need to do this retroactively.

**Comment by Askaholic** [comment]
This is replaced by the league service. Leagues are reset periodically which effectively gives us rating decay. https://github.com/FAForever/faf-league-service
