### ISSUE TITLE
Better handling of corrupt maps

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#13]
Originally reported at FAForever/fa#384 by @ChrisKitching.

Currently, it is possible for maps which are corrupt to be downloaded, only to fail at load-time.

We should have a verification step when uploading maps (which we should retroactively apply to the entire map database) to avoid this. It is probably not sensible to implement this verification at load-time, for reasons of performance and simplicity (and in any case the flavour of brokenness generally doesn't prevent the selection of an alternative map, except in the case that the failure occurs at game-start-time, in which case you are hosed).

See also: FAForever/fa#351

**Comment by micheljung** [comment]
Done in new upload mechanism, will we retroactively apply it to the entire map database?

**Comment by Rackover** [comment]
Obsolete. (Now related to the API.)
