### ISSUE TITLE
Update Readme more

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/server#131]
* `cp faf-server.example.pem faf-server.pem`
* `docker exec -i faf-db mysql -p<pw> faf_test < tests/data/db-fixtures.sql`

**Comment by IDragonfire** [comment]
@Sheeo is the pem file still needed?

mysql data is fixed here: https://github.com/FAForever/db/commit/c9ca0a3c42d52d55fa4b08b9fd3409d994dffed7

**Comment by Sheeo** [comment]
Yes, the pem file is still needed.
