### ISSUE TITLE
Use UTF-8 encoding for main protocol

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#132]
Currently the protocol uses a `QDataStream` compatible format, which implies text is encoded as `UTF-16BE`.

Since most of our data is English text, this means we incur an unnecessary 50% space overhead, and a small amount of conversion, for every message. For slow clients (Both in terms of processing and link-speed) this can especially be a problem.

**Acceptance Criteria**
- Protocol uses plain `UTF-8` encoded JSON with no other binary elements.

**Tips to get started**
- The protocol encoding is currently performed entirely by [this](https://github.com/FAForever/server/blob/develop/server/protocol/qdatastreamprotocol.py#L14)
- Replace this with a different implementation that only uses `UTF-8` and doesn't bother with legacy encoded messages
- Make sure to update explicit uses of `QDataStreamProtocol`, such as [here](https://github.com/FAForever/server/blob/develop/server/__init__.py#L65)

**Comment by Sheeo** [comment]
See https://github.com/FAForever/server/issues/124

**Comment by Askaholic** [comment]
This was added in #615. The UTF8 encoded version of the protocol is available over a second port.
