### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#14]
People are reporting issues with downloads. They appear non-recurring.

I've fixed some issues from the nginx error.log with bad links (Some people still using wrong webroots, for one), but it wouldn't explain downloads stopping half way.

**Comment by VoRGoR** [comment]
I told all the people who were complaining about it to message me again or report it directly to the previous issue. Have got nothing so far, so it's probable it just was a temporary issue.

**Comment by Sheeo** [comment]
This may be an issue with the fact that we're running `Ubuntu Precise 12` on the server, which lead to `Nginx 1.1.19` being installed. A rather arhcaic version.

There have been some fixes related to truncated responses upstream, so this may well be what some people are encountering.

**Comment by Sheeo** [comment]
I've updated the installed nginx to mainline `1.7.9`, hopefully this resolves it.

**Comment by Sheeo** [comment]
As it turned out, Varnish was the problem: It would terminate all downloads that took longer than 60 seconds. Upped this value to 600s.
