### ISSUE TITLE
HowTo: Fix coop in production

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#152]
Coop is fixed on the test server. These are the steps that need to be done to fix it in production:

* [x] Update coop missions (make sure custom ones are included)
* [x] Update coop (mod)
* [x] Upload voice files
  * [x] `*_VO.nx2`  in `content/faf/updaterNew/updates_coop_files/`
  * [x] Entries in DB table `updates_coop` and `updates_coop_files`
* [x] Update `init_coop.lua` (get from test server)
* [x] Update client (see [client #365](https://github.com/FAForever/client/pull/365))
* [x] Add new custom missions to `coop_map`:
```
INSERT INTO `coop_map` (`type`, `name`, `description`, `version`, `filename`) VALUES (4,'Prothyon - 16','Prothyon - 16 is a secret UEF facillity for training new ACU pilots. Your task today is to provide a demonstration to our newest recruits by fighting against a training AI.',5,'maps/prothyon16.v0005.zip');
INSERT INTO `coop_map` (`type`, `name`, `description`, `version`, `filename`) VALUES (4,'Fort Clarke Assault','Rework of the first FA mission from Seraphim point of view. Work in progress.',5,'maps/fortclarkeassault.v0005.zip');
```

**Comment by ChrisKitching** [comment]
> Update init_coop.lua

Isn't that in git somewhere? (Meaning you should make a pull request for it?)


... I have a horrible suspicion the answer is "no".

**Comment by aeoncleanse** [comment]
No, it's not.

**Comment by aeoncleanse** [comment]
Tested Prothyon16 again, had trouble downloading the sound files same as earlier :/

**Comment by speed2CZ** [comment]
Also updating the coop mod, not just missions

**Comment by micheljung** [comment]
@ChrisKitching maybe I'm mixing something up but I remember sheeo saying he does not want it to be in Git for some reason..

**Comment by aeoncleanse** [comment]
He has some plan to generate inits from mod_info.lua

**Comment by Sheeo** [comment]
Yes these should not be in git. They allow arbitrary code execution, and with automated deployment this allows any contributor to infect our entire user base with a mere git push.

**Comment by ChrisKitching** [comment]
> They allow arbitrary code execution, and with automated deployment this allows any contributor to infect our entire user base with a mere git push.

So does absolutely all code in any native-code open source project.
They use git.

Surely if you have even slightly not-retarded code review this is a non-problem.

**Comment by Sheeo** [comment]
Completed all the steps, yet hosted coop games do not show up in the coop list. Need to investigate this--for now; bedtime.

**Comment by micheljung** [comment]
So you see all the missions (incl. custom) and you're able to host one, but it doesn't show up in the client?

@speed2 we didn't have susch a problem did we?

**Comment by speed2CZ** [comment]
What excatly is not showing?
![ss 2016-06-30 at 02 56 53](https://cloud.githubusercontent.com/assets/10947024/16488887/0bc12b36-3ed3-11e6-84b3-bb2b54b1ef3f.png)

**Comment by Nojoke185** [comment]
tried some tests earlier with speed and my game did not show up when i hosted it
logs attached
[forever.zip](https://github.com/FAForever/server/files/341542/forever.zip)

seems to error on this:

2016-06-30 14:20:23,220 INFO     client._clientwindow           Handling game_launch via JSON {u'args': [u'/numgames 537'], u'command': u'game_launch', u'uid': 4892490, u'mod': u'coop'}
2016-06-30 14:20:23,221 INFO     fa.upnp                        UPnP mapping 192.168.1.93:6112
2016-06-30 14:20:23,230 ERROR    fa.upnp                        Exception in UPnP createPortMapping.
Traceback (most recent call last):
  File "src\fa\upnp.py", line 35, in createPortMapping
  File "<COMObject <unknown>>", line 4, in Add
com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024726), None)

**Comment by micheljung** [comment]
No issues here either, except that some previews are apparently not available on the server:
![image](https://cloud.githubusercontent.com/assets/1864183/16712684/a10d452c-468e-11e6-9de4-ad0fddbcc296.png)

**Comment by Sheeo** [comment]
All right, thanks. Will deploy the .11.60 update today then.

**Comment by micheljung** [comment]
AFAIK this is done, closing it.
