### ISSUE TITLE
Clean up server logging

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#157]
According to Loggly, the server logs almost everything with severity `error`, even things like:
```
GameConnection initializing
Saving game scores
Awaiting nat packet Hello from 34165 from anywhere
('0.0.0.0', 67): ('95.25.246.8', 64563)/udp<<: b'\x08Hello 150160'
```

Those should be logged as debug - and even better, turned off in production. The prod logs are far too noisy

**Comment by Sheeo** [comment]
Configuration issue, not a code problem. [Quick inspection shows INFO being used](https://github.com/FAForever/server/blob/develop/server/gameconnection.py#L43).

**Comment by micheljung** [comment]
So and just because it's a configuration and not a code problem means we don't fix it?

**Comment by Sheeo** [comment]
No, it means this repo isn't the correct place to track and report it. We don't have a repo for our devops/docker configuration at the moment, so use slack for this.

**Comment by Sheeo** [comment]
Regarding the debug vs. info levels: https://github.com/FAForever/server/commit/702e07fe02047f87466233c307bde208b906185d
