### ISSUE TITLE
ranked game 'dead' time issue

### ISSUE THREAD

**Issue by spooky** [FAForever/server#16]
It seems that the part responsible for deciding whether a game is ranked or not based on game time (so the N min unrakned period) has a problem. 
I've played two games: 
  3138425 - game time: 1:35 - played disconnected so we rehosted
  3138461 - game time 4:22 - another disconnect
Not sure after which one, but one of these lowered my ranking.

**Comment by Sheeo** [comment]
3138461 was ranked, the first was not.

The rule is 60 seconds per player, in the case of your latter game that amounts to 4 minutes, which it exceeds -- it was ranked according to the current algorithm, working as intended.

Code is here: https://github.com/FAForever/server/blob/develop/games/customGame.py#L44

**Comment by spooky** [comment]
Hmm, thought it's 5 min or something.... good to know, thanks for the info
