### ISSUE TITLE
Stats history still mixes custom & 1v1

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#161]
![image](https://cloud.githubusercontent.com/assets/1864183/16120038/6f0f7184-33de-11e6-956d-f78ec94175cb.png)

**Comment by Sheeo** [comment]
Incorrect repository.

**Comment by micheljung** [comment]
For global statistics, the statistics server read all games with `game_stats.gameType = 0`. So I assumed `gameType = 0` stands for "global games". But apparently, it is the "victory condition" - however in that case I have no idea why those stats weren't mixed up earlier. Were ladder games not stored in `game_stats` before?

Before [this commit](https://github.com/FAForever/server/commit/f5fc31f0fc380b746f8a733538a1ffb8bb9b0b25#diff-9e7e868d3d7a27585abd7a3be83deb85R443),
the game's `self.gameType` was used to store into `gameType`. Now it *alyways* stores the value of `Victory` (0).

So I conclude that we put global and ladder games into the same table and there is no way to distinguish between them?

**Comment by Crotalus** [comment]
game_stats.gameMod refers to the "featured_mods" table so I think it's possible to filter out stats that way, 'ladder1v1' exists in that table for instance.

**Comment by micheljung** [comment]
Right, that's what I was looking for, no idea how I could miss it :-) Guess I can create an API route then.
