### ISSUE TITLE
Server bothers with whitespace in json messages

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/server#166]
Messages from the server come out like this:
`{"session": 1842478479, "command": "session"}`

We probably should be sending minified JSON. Would very slightly help performance in the presence of large messages (like the huge game info blob you get on login). Of course, UTF-8 would have a vastly larger effect, but is slightly trickier.

**Comment by micheljung** [comment]
Last time I checked, python's JSON parser choked on missing whitespaces. I had to explicitly add them.

**Comment by Askaholic** [comment]
AFAIK the json parser can handle this fine now. I couldn't find any closed issues directly fixing this bug, but I did find an issue which added a compact flag to `json.dumps`: https://github.com/python/cpython/pull/72
