### ISSUE TITLE
Ladder rating not working correctly

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/server#185]
I gained 2 points today after losing 6 games and winning one on ladder. The losses were vs people with equal or lower rating to me and the win was vs someone higher rated.
[forever.txt](https://github.com/FAForever/server/files/366842/forever.txt)

**Comment by shalkya** [comment]
yeah i had lot of issue like that.
2091 point, then win against voodoo, 2096 point, then win against silentnoob => 2093
i may have an idea about that :

**Comment by Crotalus** [comment]
I guess that could explain it, AFAIK a game gets end-state / rating calc when all players have left the game (disconnected)

If one of the ladder players stay in game after win / loss the game will not get rated and if the other guy starts a new game it will use the old rating.

**Comment by shalkya** [comment]
i'm not sure of it, i played the 2nd ladder game 1h after my first one. Voodoo have left the game mean while.

**Comment by micheljung** [comment]
Grothe linked me: http://forums.faforever.com/viewtopic.php?f=3&t=12109&p=131626#p130960

**Comment by JaggedAppliance** [comment]
@Sheeo please check what happened to my rating during these games, I lost all three but I didn't lose points for all of them based on what I saw on the leaderboards tab.
5200522 5200531 5200543

**Comment by GrotheFAF** [comment]
all 3 replays show the same rating .. which means you didn't refaf inbetween. (current bug)

**Comment by JaggedAppliance** [comment]
I'm talking about the rating on the server, I know the score doesn't update. Leaderboards showed me gaining a point when i had lost.

**Comment by shalkya** [comment]
JA sheeo told me the only way to show him that the rating is bugged (on the leader board) is to take screen shot of leader board, before 1st game, after 1st game, after 2nd game. and to show how rating change.

**Comment by GrotheFAF** [comment]
Leaderboard showed I gained one point after wining (5203109):
The one Point (or other odd Points) thing seems to only happen, when you don't refaf.
example(5203071)
replay rating(my: 755, other: 21)	I won	leaderboard(before:755, after:762)	
difference(leaderboard - replay:7,	leaderbardafter - before:7)
no refaf, next game:
replay rating(my: 755, other: 390)	I won	leaderboard(before:762, after:763)
difference(leaderboard - replay:8,	leaderbardafter - before:1)

So it seems that the rating calculation is based on replay (= (not updated) logged in user) rating.

**Comment by shalkya** [comment]
grothe you need to do screenshoot of the leaderboard rating, writing the rating here doesn't prove anything for sheeo.
if you succeed to have a win that remove some point to you, that would finally show sheeo that something wrong

**Comment by micheljung** [comment]
Assuming that this has been solved with #229

**Comment by GrotheFAF** [comment]
not so fast young man... with the assuming.. better do the test.
just one example: today dakenho, 2 ladder games (5450085, 5450086), he starts both with the same rating. so no rating-update. (and there are more examples..  find one it's easy.)
so better reopen it.

**Comment by Viba** [comment]
Rating in client indeed isn't updating after ladder games currently, if that is related to this issue.

**Comment by micheljung** [comment]
Here you go, old man: #248
