### ISSUE TITLE
People can't join my Coop game

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/server#197]
When hosting a coop game, no one can join me. It says for them that "Host has left the lobby"
My log https://gist.github.com/speed2CZ/ae0c750eea7ee3ce7d239c9cf408cf3e
theeggroll's log https://gist.github.com/theeggroll/1dc337d6a5c49436cb014df1cedce7f0

No problem when hosting a normal game

**Comment by Sheeo** [comment]
eggroll's log only shows him successfully joining and launching a normal game. Your log shows some people trying to join but not succeeding, but the reason isn't clear. Please try and gather more logs.

**Comment by speed2CZ** [comment]
ok, another try

My log https://gist.github.com/speed2CZ/9738669eb38746cbc552a2eb54c7dd54
theeggroll's log https://gist.github.com/theeggroll/0eec10b496b5ef33f7f9f5e7acd22f64
Typo's log https://gist.github.com/speed2CZ/d358fa5f2fafdd46917463510aed2cf5
WittySeal's log https://gist.github.com/speed2CZ/5fa4f90f99aea136a584739fdb1a4e7a

**Comment by theeggroll** [comment]
People can't join my games period, ill be posting as many logs as I can get on this issue
FTXCommando trying to join my game: https://gist.github.com/anonymous/f48cf4139c2bf9a48f4837cc68bb83e1

**Comment by HardlySoftly** [comment]
This happened to me, and there is nothing interesting in the log.

I suggest what we really need is server logs.
