### ISSUE TITLE
Disconnect to one player after +-10min

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/server#205]
Pretty much every 2nd or 3rd game I lose connection to one player after about 10 minutes ingame.
My logs:
forever https://gist.github.com/speed2CZ/baba61c80678bedfe403b258384daa43
game https://gist.github.com/speed2CZ/d0e3fd23728c1ece5fb0f9f9fd440d4c
Rumadai (Tokyto__) logs:
forever https://gist.github.com/speed2CZ/d464d41e23b7808dde096b2d543ac661
game https://gist.github.com/speed2CZ/e720754f8aeb18c07ae6b8ec2c0b6d27

**Comment by Uveso** [comment]
hi Speed,

i don't found a direct cause for an error inside the logs.
But i f i compare your log with Tokyto's log, then your log has massive warning spam.

Maybe a UI mod, that Tokyto is not using ?
This mod is maybe delaying the game and you get a disconnect then ?

I dont see a cause for a disconnect inside the logs itself.

**Comment by HardlySoftly** [comment]
The forever logs for speed2 don't contain any reference to the id of the game in the two game logs (5192891), and Tokyto's log only contains the very tail end of what was going on (log rotation I guess).
