### ISSUE TITLE
Wrap unit test database sessions in transactions

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#219]
This allows us to maintain unit test seperation w.r.t. database state.

**Comment by Crotalus** [comment]
Would also be nice with a SQLite in-memory option so you can run unit tests ultrafast / without need of a mysql instance.

**Comment by micheljung** [comment]
Yes, but that's not easily possible because SQLite and other in-memory DBs have different syntax than MySQL.
Also, I saw we're currently using MEMORY as storage engine for tests, but that doesn't support transactions (http://dev.mysql.com/doc/refman/5.7/en/memory-storage-engine.html).

**Comment by Askaholic** [comment]
#494
