### ISSUE TITLE
Maps being downloaded into wrong folder for user with special characters

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/server#222]
We have this in the init file
```LUA
-- these are the classic supcom directories. They don't work with accents or other foreign characters in usernames
mount_contents(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods', '/mods')
mount_contents(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\maps', '/maps')
 
-- these are the local FAF directories. The My Games ones are only there for people with usernames that don't work in the uppder ones.
mount_contents(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods', '/mods')
mount_contents(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\maps', '/maps')
```
to load maps from ProgramData folder if the user has some special characters in the default user name since the game doesn't handle it (for example russian characters Документы, etc ...)

But when those people are downloading maps it downloads them into MyDocuments and then the game can't load it and they'll get the error that they're missing the map.

If they move the map file manually into the folder in ProgramData, it works.

**Comment by micheljung** [comment]
This isn't a server problem

**Comment by speed2CZ** [comment]
A client problem then?

**Comment by micheljung** [comment]
Yes it's client side

**Comment by speed2CZ** [comment]
Alright moved https://github.com/FAForever/client/issues/428
