### ISSUE TITLE
Player reported as "in game" even though they're not

### ISSUE THREAD

**Issue by Viba** [FAForever/server#224]
After the server update, crossed swords were shown for people in a lobby.

Also crossed swords are shown for people who were in a lobby, even though they left and are not playing.  Viewing live replay for these players also opens up the game for the lobby where they were, even though they aren't playing.

**Comment by Crotalus** [comment]
When the server rating issues stabilize we need to confirm if this still is an issue, it's been throwing some exceptions when games are ending.

**Comment by micheljung** [comment]
I have a feeling that this and the "rating not updated" have the same cause.

**Comment by WolframiumR** [comment]
i have this bug too - i'm not in game but have crossed swords

**Comment by Askaholic** [comment]
Happens because player list is frozen at the start of a game. Players are not shown as being out of the game until the sim has ended, so anyone who does early will appear in game although they’re not.

New issue #703
