### ISSUE TITLE
Game stats are reported too early

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#228]
```
2016-10-13 01:32:38.935
Processing game stats for player: Downlord
2016-10-13 01:32:34.483
Processing game stats for player: Pickral
2016-10-13 01:32:31.599
Processing game stats for player: Boofy
```

This happened after Boofy left. I was in the game until 01:52. The stats were reported for some players, not for all.

**Comment by Crotalus** [comment]
Could part of the problem be #229 when it crashed during stats processing, thus stopping after Boofy?

The reason for stats being sent before game was ended... was observers on? That would turn Boofy into an observer after death. If I'm reading the score code correct, someone with focus army -1 (observer) will trigger a full score sync, including stats.

**Comment by micheljung** [comment]
I don't know if it were Boofy's stats that couldn't be processed, had to check the log again, but I think it was not. But yes that would be an explanation. 

The server is meant to process stats of any player as soon as their army result is reported (because they should get their achievements straight away), and of all remaining players (who can even be remaining, disconnected ones?) when the game ends.

So in order for the stats to be processed, the army results needed to be reported before I finished - how?
