### ISSUE TITLE
Enable UUID check again

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#240]
The code is there, but it needs to actually prevent login https://github.com/FAForever/server/blob/develop/server/lobbyconnection.py#L626

**Comment by sir-ragna** [comment]
I can't sign in anymore. 
As I get the following message.

![image](https://cloud.githubusercontent.com/assets/1280559/20501172/02403fb6-b039-11e6-93b3-76f760340678.png)

I redid the procedure to link my steam account again (was already in place), yet it didn't seem to work.

And it also seems that I am not the only one.
https://forums.faforever.com/viewtopic.php?f=3&t=13539

I appreciate the efforts to reduce smurfs but this is blocking legitimate players at the moment.

**Comment by duk3luk3** [comment]
@sir-ragna did you read http://www.faforever.com/2016/11/2016-11-21-server-update ?

**Comment by sir-ragna** [comment]
@duk3luk3 I did. Multiple times even just to check that I didn't miss anything.

I even went through the account linking procedure for a second time again.

![image](https://cloud.githubusercontent.com/assets/1280559/20501975/65fa8a68-b03c-11e6-84c0-7d8c122fb9c1.png)

No change however.

Other things I've tried

- Rebooting PC
- verifying that faf is executed as admin

So this indicated either an issue with this patch or an issue with the linking process.

**Comment by micheljung** [comment]
What's your FAF username?

**Comment by sir-ragna** [comment]
> rrragnarok

**Comment by micheljung** [comment]
http://www.faforever.com/2016/11/resolving-multiple-account-issues/#.WDN4GrKLSUk

**Comment by sir-ragna** [comment]
@micheljung thanks for the quick update. It works now for me.

I'll try to keep an eye open for scenarios to reproduce this issue. Since I share my PC with someone else and use multiple PCs.
