### ISSUE TITLE
Old clients cannot get a session

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/server#258]
Currently, the server only lets the most recent client version connect.

https://github.com/FAForever/server/blob/develop/server/lobbyconnection.py#L656

```python
    def check_version(self, message):
        versionDB, updateFile = self.player_service.client_version_info
        update_msg = dict(command="update",
                          update=updateFile,
                          new_version=versionDB)

        self.user_agent = message.get('user_agent')
        version = message.get('version')
        server.stats.gauge('user.agents.None', -1, delta=True)
        server.stats.gauge('user.agents.{}'.format(self.user_agent), 1, delta=True)

        if not version or not self.user_agent:
            update_msg['command'] = 'welcome'
            # For compatibility with 0.10.x updating mechanism
            self.sendJSON(update_msg)
return False
```

https://github.com/FAForever/server/blob/develop/server/lobbyconnection.py#L820

```python
    def command_ask_session(self, message):
        if self.check_version(message):
            self.sendJSON({
                "command": "session",
                "session": self.session
})
```

I believe this should be changed so users can downgrade their clients if there is a problem.

For example, we could list more than one version in the `version_lobby` table and adapt the server code shown above accordingly.

Some people have also suggested removing the version check from the server entirely and letting the client decide what to do.

**Comment by Rackover** [comment]
I would advocate for the latter. There's a similar discussion going on on PR https://github.com/FAForever/server/issues/258
I'm closing this issue for now to avoid a duplicate discussion.
