### ISSUE TITLE
use secure key length for uid

### ISSUE THREAD

**Issue by muellni** [FAForever/server#259]
@micheljung reported https://github.com/FAForever/uid/issues/3 to increase the RSA keylength from currently ~224 bits to 1024(?) bits.

This issue needs to be addressed at server and client update simultaneously.
Since a first rollout of `faf-uid.exe` will happen in client 0.12.0, we could address this problem there.

Is this a problem which needs to be solved? If so, 0.12.0 release would be an opportunity.

**Comment by Rackover** [comment]
Closed, no longer relevant to the server since the UID check is operated by the faf-policy-server.
