### ISSUE TITLE
rating is always calculated based on player rating when game started

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/server#265]
join a game -> die in game -> join another game -> score of game that finished first doesn't count

probably needs to be fixed by updating the player rating from db before calculating new rating

**Comment by GrotheFAF** [comment]
was the first game over or still running, before joining another game?
(the later is a tricky problem.)

**Comment by duk3luk3** [comment]
The problem is with the first game still running.

>  (the later is a tricky problem.)

I don't think so - all you have to do is refresh the player rating from the db before updating the rating.

**Comment by GrotheFAF** [comment]
The players ratings are not calculated before the game is over. (last player reported)
On what basis would you calculate one players rating if the game is still ongoing? you don't even know if the player is on the wining team.
The bigger problem is probably to queue up and process results (preferedly in the right order) and not lose any results, if the second game finishes before the first, and the player enters a third... not a rare case.

**Comment by duk3luk3** [comment]
we only have a real problem if the second game finishes before the first one does.

**Comment by Katharsas** [comment]
When the server calls Trueskill to update the rating of players, it should pass the current rating (from db at that moment in time) instead of stored ratings from the beginning of the match.

**Comment by Askaholic** [comment]
I see. So the rating change of the second game completely overwrites the rating of the first game. Yea that seems pretty straight forward to fix
