### ISSUE TITLE
ICE: Get Twilio NTS Token

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/server#271]
To use [Twilio Network Traversal Service](https://www.twilio.com/docs/api/stun-turn) properly we need to add a way for the server to generate NTS tokens and give them to a client.

NTS tokens are valid for 24 hours.

Therefore, I propose the following:

1. Add a task to the server that fetches a new NTS token from twilio once per hour
2. Add a server command `nts_token` that can be used by any authenticated client and returns the token.

We **may** have to change this to give a separate token to every client, i.e. fetching a new token from twilio for every `nts_token` request.

Open questions:
* Should we limit the lifetime of the token?
* In which ways can this token be abused? Can we detect abuse and ban players abusing?

I will start with the implementation and push a PR asap.

**Comment by muellni** [comment]
I'd like rather hide twilio from the client and only transfer the `iceServers` list. This list should get a lifetime. And it should contain our own STUN/TURN-server(s).
The servers can be abused by generating traffic which we have to pay for, but the credentials have a limited lifetime, so the risk is limited. 
Furthermore I'd suggest to increase the lists lifetime, maybe 10 hours, to not interrupt someones FAF evening.

**Comment by duk3luk3** [comment]
oh, the iceServers list already includes the credentials for the turn/stun servers in it?

Could you post an example of a full ntstoken in here (without real auth keys ofc)

**Comment by duk3luk3** [comment]
What would the temporary username and password be used for that you get from the token? What capabilities does it give?

**Comment by muellni** [comment]
If you're refer to the credentials in the iceServers list, its only used for allocating the TURN session afaik.

**Comment by duk3luk3** [comment]
I made a PR; it is missing

> it should contain our own STUN/TURN-server(s).

How would those look like?

**Comment by muellni** [comment]
like this: ```this.iceServers = [
      {
        urls: [`turn:test.faforever.com?transport=tcp`],
        credential: 'test',
        username: 'test'
      },
      {
        urls: [`turn:test.faforever.com?transport=udp`],
        credential: 'test',
        username: 'test'
      },
      {
        urls: [`stun:test.faforever.com`],
        credential: '',
        username: ''
}];```

**Comment by duk3luk3** [comment]
How do we put that into the server? JSON file in a mapped server?

**Comment by muellni** [comment]
I'd use some ENV var in the docker-compose file. Same for the twilio auth secret.

**Comment by muellni** [comment]
According to http://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api we could basically start coturn with `--use-auth-secret --static-auth-secret=my_secret` and generate the ephemeral credentials in the python server by using the secret... sounds perfect.

**Comment by duk3luk3** [comment]
Sounds great!

Also this:

> Hi Martin, Thanks for contacting Twilio Technical Support and my apologies for the delayed response to your question. We recommend that you do one token per user, or one toke per call as we do not charge by the token – you should scope the token lifetime appropriately. You will get a similar ICE server list, but with different credentials. I hope the information I have provided is helpful. Please let me know if you need any further assistance, or have any questions about the information I have provided. Thank you, Jim

**Comment by muellni** [comment]
I suggest:
- Let the client make a request after welcome then when TTL is reached
- Let the server generate a new Token for 24h when no current Token for player or current TTL is <12h

**Comment by duk3luk3** [comment]
Nah, I don't want to keep track of every client's token in the server. I don't see a particularly good reason to do so.

**Comment by duk3luk3** [comment]
Also

> If you refer to the credentials in the iceServers list, its only used for allocating the TURN session afaik.

No - the token itself contains a username and auth token. I'm wondering what that gives you access too.

**Comment by muellni** [comment]
So we take 
> We recommend that you do one token per user
only as recommendation and use one token for all users? This would certainly be easier if it works.
Or do you want to to create a token per user, but store it client-side? 
I'd still prefer hiding twilio from the client entirely. The token itself has no use on client-side and the STUN/TURN service is easier exchangeable.

**Comment by visionik** [comment]
A few thoughts... we should add a FAF server API call to get an auth token, and when it's called by the client have the FAF server immediately call the Twilio API and get and then return an auth token.  I'd avoid any caching, tracking, expiring, etc. in the server or the client.   Just call the FAF server API to get a new token each time a client hosts/joins a game.

I think 12 hour lifetime is fine.   I've never seen a game go that long (including lobby time).

**Comment by duk3luk3** [comment]
Yes, that's exactly what I implemented in my PR :-)

I think muellni has been misunderstanding me.

**Comment by muellni** [comment]
k, I can't find anything about a twilio rate limit on google, so this should be fine.
