### ISSUE TITLE
Lobby Name change doesn't work

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/server#274]
When i change the name of a lobby it doesn't update.
[logs](https://puu.sh/upGeO/3a47171dd0.zip) are in the link
[screenshot](https://puu.sh/upGzv/a4b36b6c47.png)

**Comment by GrotheFAF** [comment]
was a client issue. fixed in client/#690

**Comment by PhilipJFryFAF** [comment]
sweet works in the preview now!
another thing that bugs me a little is when i change the lobby name to nothing the box to change the lobby name becomes impossible to click on

**Comment by GrotheFAF** [comment]
yep, that's a bug. 
empty title shouldn't be possible, it should reshow the inputbox until it's not empty.
But that is fa-department ... you take the stairs at the end of the corridor two floors down and then....

**Comment by PhilipJFryFAF** [comment]
well i guess i can close this issue here then

**Comment by GrotheFAF** [comment]
It's your issue, you can close it.
