### ISSUE TITLE
recent Ladder Replay (2017-03-06) saved with wrong version 3672

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/server#277]
pleae checkout: 5898432 (BRS_DCCC97 v This_Guy on The Bermuda Locket) it uses v3672
(the game desync right away)
same with:
faf: 5892147 (This_Guy  - Testing stuff out (alone)) from 2017-03-05 uses v3672
ladder: 5870419 (This_Guy v TA4Life) and 5870315 (This_Guy v TA4Life) from 2017-02-28 use v3672
ladder games from 2017-02-27 and -26 show 'normal' v3675 
but:
faf: 5859947 (This_Guy  - Testing stuff out (alone)) from 2017-02-26 uses v3672 again
(checked a few games before that normal v3675)

**Comment by duk3luk3** [comment]
Why do you think this is a server issue?

**Comment by GrotheFAF** [comment]
I talked with This_Guy ... probably his PC-something.
