### ISSUE TITLE
Game titles seem to be quoted needlessly

### ISSUE THREAD

**Issue by Wesmania** [FAForever/server#282]
The lobby connection uses `cgi.escape` to escape game titles. From what I can tell the server does not need this encoding for anything, as it doesn't use the "title" field other than receive it and send it. The client always receives a game as a "game_info" command - apart from passing it around and sending it back, it prints it in a couple of places where it uses HTML escaping (tooltips, game widgets), and places where it doesn't (live replay tabs). This causes escape sequences to print in a couple places.

Escaping the game title seems needless, and there are places where we would need to unescape it in the client. We should fix the client and start sending the title unquoted.

**Comment by MartijnPieterse** [comment]
I'll give this a go.
