### ISSUE TITLE
Explicitly set endTime

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#289]
Depends on FAForever/db#84.

`game_stats.endTime` needs to be set explicitly.
It's not easy for the server to know when a game actually finishes; right now it assumes a game to have finished when the last player disconnected. This causes #263. From my analysis, the best way to determine if a game finished is if either:

* All connected players reported army results for all players
* There's no more player connected

Even better may be to have the game send a `GameEnded` message, because the game end may actually not be coupled to the army result report (in fact, I think the current game code ends the game 5s after the last score report). But for now the above will suffice.

**Comment by Wesmania** [comment]
It's really surprising to me that the legacy server references EndTime in game_stats, yet doesn't failt anywhere, even producing some results. Why would that happen?

**Comment by Wesmania** [comment]
I did some digging, I guess the most fitting message to consider as game end is 'GameResult'.

**Comment by micheljung** [comment]
For the protocol: We figured out why the missing EndTime doesn't cause failures in the legacy replay server; its code has been modified server-side but not commited to GitHub.
