### ISSUE TITLE
Broken rating

### ISSUE THREAD

**Issue by JeroenDeDauw** [FAForever/server#30]
Either this stuff fatals or my IDE is being fail.

https://github.com/FAForever/server/blob/develop/src/gameconnection.py#L836-L845

![refs](https://cloud.githubusercontent.com/assets/146040/6766299/5d7a50f2-d001-11e4-92c9-e22d30222281.png)

**Comment by Sheeo** [comment]
It will. It's being reworked on the `refactor/rating` branch.

The previously included trueskill code was broken when moving to python 3, and I've chosen not to try and port it, relying instead on [this library](http://trueskill.org).

**Comment by JeroenDeDauw** [comment]
What's the plan with this `refactor/rating` branch? And why is this stuff happening on a diverging branch anyway? Somewhat annoying to deal with no?

**Comment by Sheeo** [comment]
It is to seperate the state of work on the networking side from work on getting the rating working again.

Branching and merging/rebasing with git is bliss and not a problem.
