### ISSUE TITLE
Win ratio for ladder doesn't work

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/server#300]
It's been broken since (i think) february 2016 when the server was changed/updated.

**Comment by Askaholic** [comment]
Apparently this is still not working correctly. https://forums.faforever.com/viewtopic.php?f=3&t=17309

**Comment by Askaholic** [comment]
Played a test game, and it looks like the database was updated correctly:

```
UPDATE ladder1v1_rating SET mean = 16.7847118883143, is_active=1, deviation = 34.1293986251118, numGames = numGames + 1, winGames = winGames + 1 WHERE id = 161739
```
