### ISSUE TITLE
Game stats and player ratings aren't updated before last player disconnects

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#316]
The endTime of a game [is set when the game ended](https://github.com/FAForever/server/blob/develop/server/games/game.py#L333).

One might expect that a game that has its `endTime` set also has the results of the game, and that all players have their rating updated. However, these things happen in `on_game_end` which is not called when the game ends, as one might expect as well, but when the last player decided to close his game instance.

This not only causes problems because users of the API can't rely on the game status/endTime but also makes the rating overlapping problem even worse than it already is.

**Comment by GrotheFAF** [comment]
see #263 ..maybe.
