### ISSUE TITLE
Make ladder map selection non-random

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/server#319]
Introduce a non-random selection code to exclude the last played map of both players before rolling the dice. This will improve player perception of how random it is and avoid strings of playing the same map.

We could also add more maps to the pool to get a little more variety, and it would feel nice with this in place.

**Comment by FtXCommando** [comment]
Have the code look at the last 3 maps of each player. Take these 3-6 maps out of the potential pool of maps for this specific match between said players. 

If possible make the parameter that tells the system how many maps it should look at fairly simple to change. When different ladder systems are decided upon in the future it may be necessary to downscale the quantity of maps that the system looks at.
