### ISSUE TITLE
Server is sending empty strings as countries for some players

### ISSUE THREAD

**Issue by Wesmania** [FAForever/server#320]
This is happening since last server migration.

**Comment by GrotheFAF** [comment]
maybe https://github.com/FAForever/server/blob/develop/GeoIP.dat needs an update

**Comment by MathieuB8** [comment]
Yeah I've looked in python file and you are most likely right. 
I've done a PR about that (didn't test it because I can't for the time being)

**Comment by duk3luk3** [comment]
If we can install this file on the server, we should just map it as a volume instead of carrying it in the git repo.

**Comment by MathieuB8** [comment]
Ugh..? You are thinking about docker I guess ? (no clue how to do what you said, never used docker before..)
