### ISSUE TITLE
Players' are matched within too small a rating range for their first ladder game

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/server#336]
I think there must be a bug with matchmaking for the first game because the rating range people can be matched in is small, although they have a high deviation. They are matched versus someone ~1300 rated, give or take 100 points, which is a very small range and leads to people having difficulty finding their first game. 

This range is also not very active on ladder creating very long wait times for new players.

**Comment by Rackover** [comment]
bea572b6ca5649879b9c55a30f415abf208b5f7a
Should be okay for now
