### ISSUE TITLE
couldn't host game

### ISSUE THREAD

**Issue by shalkya** [FAForever/server#337]
i guess it's a server issue. First time i had this warning.

happen after trying to host a faf game. => nothing happening
tried again and then i got this odd message : ![image](https://user-images.githubusercontent.com/11618427/36639667-a52bbcfc-1a5d-11e8-86b6-7842e0224451.png)

looked into task manager, no fa game were ran in the back.

[forever.log](https://github.com/FAForever/server/files/1755831/forever.log)

refaf didn't fix it, i had to reboot compter.

**Comment by Sheeo** [comment]
You most likely had a shadow/dead client running in the background, preventing it from listening on your ports properly. Can't fix without further steps to reproduce.
