### ISSUE TITLE
Make version check for java client

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/server#358]
https://github.com/FAForever/server/blob/7e6d2abe936b21d056da3671d5bbafda22788912/server/lobbyconnection.py#L491
Just add an if in case it is the java-client , add an env variable, if env varibale is lower version raise a ClientError-> so no session is opened and the user is shown an error(e.g. Please download a newer version of the client, have a look in your notifications for the newest version)

**Comment by axel1200** [comment]
@Michel Jung what are you thoughts on this

**Comment by micheljung** [comment]
My thoughts: The server shouldn't know about client versions and it shouldn't be the one to tell the client that an update is available. Especially not hard-coded.

Instead, the server should specify a protocol version which follows semver and allows the server to detect if a client is not compatible. In such a case, the connection will be rejected.

**Comment by Rackover** [comment]
I think not. 
It's not up to the server to say that someone's client is outdated, therefore the server *should not* check the version of the client nor have to do it.
Does that client send me stuff I understand ? Yes, then I communicate. No, then I close connection.
It's already working like that, there's nothing to add - we should just remove that version check. It's ancient, unpractical, unneeded.
The clients should handle their own updates, either with the API or the way they want, but the game server should not be implicated in that story.

**Comment by Rackover** [comment]
Then it's protocole version that should be exchanged, not client version.
Let's standardize those protocols first in a document so we know what is "Protocol V1", "Protocol V1 - ICE", "Protocol V2", and then we can make checks in the server when communicating with the client (the client will indicate which protocol it wants to use - Protocol 1 will be assumed if nothing is sent).
Server should not have to know which client versions exist.
