### ISSUE TITLE
Allow opt-out of GeoIP identification

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#395]
People who do not want their country known for privacy reasons should be able to opt out of geoip country identification at any time. 

If someone opt's out the server should respond as if their country was not found in the database.

**Comment by Brutus5000** [comment]
As this is a controversal topic I have initiated a poll in the council regarding this feature request. The intermediate result reflect this. Right now it is a 3:3 draw, with an additional 3 votes missing.

**Comment by Brutus5000** [comment]
The council has decided that hiding the country flag is an acceptable feature.

**Comment by Rackover** [comment]
Awesome - let's get this running.
Who can handle the API part ?

**Comment by Brutus5000** [comment]
Not interested. Furthermore, several people already announced that they would offer an alternative source for the flag if it is removed from the server.

**Comment by Rackover** [comment]
I don't see any reason for that comment to be here. If you're unhappy with the council decision, you can talk about it on slack - not on the python server issues section.

**Comment by Brutus5000** [comment]
You asked a question about something not server related and now you complain about the answer being not server related?
