### ISSUE TITLE
Newly Added Friends and Foes are not saved

### ISSUE THREAD

**Issue by ThomasHiatt** [FAForever/server#414]
Any newly added friends and foes are not saved once the client is closed. You can add someone as a friend, restart the client, and they will not be on your friends list anymore. Same for foes. I tested in both python and java client.

**Comment by Askaholic** [comment]
This is happening because of a decorated async function. The decorator here:
https://github.com/FAForever/server/blob/292604949ea248dfbadca8ffed97ce3dafa9cdc7/server/lobbyconnection.py#L249
Tries to call the function it's wrapping with sync syntax meaning that the function is never awaited.
