### ISSUE TITLE
Ladder matching hugely different ranked players too easily

### ISSUE THREAD

**Issue by JonnoHR31** [FAForever/server#427]
The ladder system currently seems to prioritise speed of matching over matching with someone of a close rank, resulting in many horribly unbalanced games. 

Today I experienced - insta-matching with someone 5 times my rank (200 vs 1000). I quit immediately (pointless game), only to then insta match with a 600 rank. 

All this whilst over 800 players were online. If the system simply waited a little bit longer, the rank deviation could be significantly reduced.

**Comment by Askaholic** [comment]
Thanks for the report! This would hopefully be alleviated by Sheeo's proposed changes in #422.
