### ISSUE TITLE
Enhance testing with hypothesis

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#454]
Hypothesis is a great library for writing better unit tests, but it is generally more effective on testing functions that manipulate strings, or other complex data as those have many more weird edge cases. 

[Hypothesis Documentation](https://hypothesis.readthedocs.io/en/latest/)

I want to use this issue to keep track of potential candidates for `hypothesis` unit tests and if I find enough, then maybe I'll add hypothesis to the dependencies.

### Candidates:
- QDataStreamProtocol
- Matchmaker Algorithm - For generating graphs

**Comment by Rackover** [comment]
I'm glad we finally plan to remove this 😃
