### ISSUE TITLE
Adjust config parameters without server restart

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#455]
Currently the config parameters are only read on server start (when `config.py` is imported) which means that adjusting them requires a server restart. It would be nice if we could adjust config values without all of the issues of restarting the server.

### Ideas
- Reload the config variables on a fixed time interval
    - Simple to implement
- Trigger config reload via some sort of communication protocol
    - More complicated
    - More security concerns
    - Could be used for triggering other server functionality such as scheduling impending downtime

**Comment by norraxx** [comment]
Docker allows file/directory binding, i think it's `-v` parameter for simple docker, you might want to bind it from outside (don't know how it's with docker-compose), and implement signal handler, for `hup`. Then send the signal with `docker exec kill  -HUP <pid>` or `killall -HUP <process name>`.

Python configuration can be reimported directly like whole python module.
```
try:
    import config
except ImportError:
    ...
```

**Comment by Rackover** [comment]
I'm up for 1 (reloading at a fixed time interval)
Easiest, safest, fastest.
