### ISSUE TITLE
Fix broken stats collection

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#474]
In particular the user agent collection is a bit buggy and often shows negative values.
Instead of using separate guages for each user agent, we should:
- [ ] Use 1 "client connected" metric and tag it with the user agent
- [ ] Tag it with user_agent version as in: https://github.com/FAForever/server/pull/260

Other things:
- [ ] Remove `connections.aborted`. It doesn't seem to provide any useful info
- [ ] Figure out a better data format for ladder match quality
- [ ] Add a guage or counter for the number of active games
- [ ] Player count is only updated when someone logs in, not when someone disconnects

Maybe ditching `aiomeasures` statsd and switching to https://github.com/prometheus/client_python could help improve things. It would also give us CPU and memory usage as well.

**Comment by cleborys** [comment]
I am not sure what is meant by "a better data format for ladder match quality" @Askaholic.
Is this already solved by making it a `Histogram` or `Summary` from the prometheus_client module?

Given that it is just a stream of floats between 0 and 1, I don't see why the format needs to be complicated.

**Comment by Askaholic** [comment]
Yea I think that will cover it.
