### ISSUE TITLE
Don't log user credentials

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#477]
There are a few log statements which currently log messages containing user passwords. This means that server admins have to be very careful to filter out lines with passwords before distributing the log file. As a result, getting server logs into the hands of the people who need them for debugging is a painful process.

When logging messages in LobbyConnection we should check if the messages contain a `password` field, and replace it with "****". 

We will also need to find a solution for not logging IRC passwords which currently happens due to aiomysql auto-logging feature.

**Comment by Rackover** [comment]
The hacky solution would be to add a grep filter in the logger that checks for the presence of the IRC password message format and replaces the md5 pass with ****

**Comment by Askaholic** [comment]
That might actually be a decent idea. Just write a filter and attach it to the logger. That's probably more reliable than trying to find every logging statement and filtering it before hand.

https://docs.python.org/3/library/logging.html#filter-objects

**Comment by Askaholic** [comment]
Was fixed by #504
