### ISSUE TITLE
Game winner determined incorrectly for Trueskill ratings

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#485]
The rating code simply sums up players scores to guess who the winner is when calculating trueskill ratings. The problem is that this is not how scores are intended to be interpreted, so it can lead to wrong results.

Code in question:
https://github.com/FAForever/server/blob/6ca91aaea49213d2cbbe316c9c2c0f1d53d82228/server/games/game.py#L899

Example game:
https://api.faforever.com/data/game?filter=id==9998778
```
team 3 (lost) scores: 1, 1, 1, -10
team 2 (won) scores: 10, -10, -10, 2
```
When you sum up the scores and multiply by -1 you find:
```
team 3 rank 7
team 2: rank 8
```
Since the code passes these numbers in as 'ranks', Trueskill interprets lower numbers as being better and hence considers team 3 to have won.

This would be a great opportunity to refactor the rating code (it's a horrible mess) as well as add some proper tests with edge cases like this. The code probably doesn't need to look at the score numbers at all, and can simply search for players who's scores were reported with the 'victory', 'defeat', 'draw', or 'mutual_draw' strings. If this is not possible, it may be good enough to search for the team which has a player with a score of +10, as this appears to be reported only for players who's ACU's are still alive at the end of a game. In the case of a draw, there may not be any players with a score of +10.

**Comment by cleborys** [comment]
Possibly noteworthy: I believe `LadderGame' overwrites how the scores are retrieved such that it only depends on whether the game was won or not.
(See [here](https://github.com/FAForever/server/blob/b04818f305a94f494032092894dacec41fe0ce82/server/games/ladder_game.py#L29).)

I assume this is an ad-hoc hack so that the score is irrelevant in ladder games?

**Comment by Askaholic** [comment]
Yea, ladder games always have a `1` or `0` score. Not sure what the original reasoning for that was, but it does make it easier to tell who won the game just by looking in the database. For custom games, there is actually no straightforward way of getting game outcome information from the database since it just stores the raw scores.

**Comment by andreasley** [comment]
**Example of a wrongly rated game (Team 2 won, but wasn't awarded any points ):**
![image](https://user-images.githubusercontent.com/1769714/70865631-e5718e00-1f5f-11ea-910a-a74219b9e99d.png)
https://content.faforever.com/faf/vault/replay_vault/replay.php?id=10678231

**Example or a weirdly rated game (Team 2 won, but zwieback received negative points):**
![image](https://user-images.githubusercontent.com/1769714/70865666-3bdecc80-1f60-11ea-8915-049a8edf1e6c.png)
https://content.faforever.com/faf/vault/replay_vault/replay.php?id=10678839
