### ISSUE TITLE
Game close message wording

### ISSUE THREAD

**Issue by Katharsas** [FAForever/server#499]
Close game message
![close](https://user-images.githubusercontent.com/1922573/67159117-badccd80-f340-11e9-87e8-45709cbe6f0d.JPG)
should be "by a moderator" instead of "by an administrator"

Relevant code:
https://github.com/FAForever/server/blob/develop/server/lobbyconnection.py#L272

**Comment by Askaholic** [comment]
We should move this message entirely to the client to take advantage of it's localization capabilities. Instead of sending English text let's send something like:
```
{
    "command": "close_lobby",
    "initiator": "PhilipJFry",
    ... any other fields that we need
}
```

See issue  #444.
