### ISSUE TITLE
Contact policy server on steam linked accounts

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/server#503]
Currently UID data is not being written due to the policy server not being informed about the login attempt. It should contact the policy server but ignore the result in case of a steam linked account.

**Comment by Askaholic** [comment]
Are you saying the policy server should be contacted on every login? Right now the steam link check happens before the policy server request. So if you don't have your steam account linked, you will be rejected before the server even has a chance to contact the policy server. So it will only contact the server if you DO have your steam account linked, but you are saying we should ignore this result?

**Comment by Geosearchef** [comment]
yes, we want to have steam link overriding the policy system from a user standpoint, so they don't get checked, but we also want to have the UID information written to DB.

**Comment by Rackover** [comment]
A steam linked user is allowed to use a VM or to have multiple machines on a single account. However if the policy server tells us that user is "fraudulent", then despite steam linking, we should just apply a ban just in case (might be trying to fake their uid .. etc)
