### ISSUE TITLE
User can select all avatars

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/server#57]
If the user know the url of the avatar he can select all available avatars:
https://github.com/FAForever/server/blob/develop/src/lobbyconnection.py#L2003

Note:
The avatar is always removed, also if the avatar url is invalid.

**Comment by Sheeo** [comment]
No, the `UPDATE` query filters on the `avatars.idUser` column. A row will not exist if the user does not have the avatar 'assigned', and thus no update is performed.

**Comment by IDragonfire** [comment]
you are right ...

**Comment by IDragonfire** [comment]
shame on me i miss the subquery ...
