### ISSUE TITLE
Map Repetition Function for Ladder 

### ISSUE THREAD

**Issue by FtXCommando** [FAForever/server#577]
Not sure if this is the correct place, but it looks like the server takes into account all types of games with the map repetition function. It should only use the specified "mod" of ladder1v1 or eventually matchmaker in determining this.

![ladder 2 maps](https://user-images.githubusercontent.com/43039749/79755685-83e37680-82e7-11ea-9294-b2bd643be749.png)

**Comment by Askaholic** [comment]
No this is not the issue. In that image you can see the ladder games are played 8 days apart. The anti-repetition only takes into account games that are less than 1 day old.

**Comment by FtXCommando** [comment]
Ah gotcha, didn't realize that was part of the system.
