### ISSUE TITLE
Upload map/mod without login/session check

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/server#60]
Upload map/mods don't check login/session variable

https://github.com/FAForever/server/blob/develop/src/lobbyconnection.py#L369
https://github.com/FAForever/server/blob/develop/src/lobbyconnection.py#L487

Is that okay?

**Comment by Sheeo** [comment]
We should generally be working on the assumption that any communication after the initial handshake is authenticated communication, so we should not need to check this here.
