### ISSUE TITLE
Add `game_type` to `game_info` message

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#605]
The client needs a way to distinguish between different types of games such as coop, custom and matchmaker games. Currently this is done by looking at the featured mod which the game uses, but this has limitations in that it doesn't allow game types to play on arbitrary featured mods (for example nomads coop, or the fact that the ladder1v1 featured mod is simply a pointer to the faf featured mod). 

For now this is not implemented in the database, but we could already define an enum like:
```python
class GameType(Enum):
    COOP = 0
    CUSTOM = 1
    MATCHMAKER = 2
```
and send these values to the client in the `game_info` message.

Original:
~The client will need to know the `init_mode` for games in order to determine whether they should appear in the custom games screen, whether players should be allowed to manually join them by other means, and how to display them in aeolus .~

**Comment by Brutus5000** [comment]
I'd rather suggest adding a game type as described in https://github.com/orgs/FAForever/projects/8

**Comment by Askaholic** [comment]
I feel like init mode makes more sense because it is the fundamental reason why you should not try to join a ladder game manually. Init mode signifies that "hey this game is an automatch, setup is handled entirely by the server" and it doesn't matter what featured mod you are playing. Heck it could be coop automatch, but the important thing is that you don't try to join it in the "custom lobby" mode because that will break things (actually it will get rejected by the server because we already added a check for `init_mode` to the `game_join` command).

**Comment by micheljung** [comment]
`init_mode` is an implementation detail of the game, the server shouldn't assume anything about it. It should rather send some generic value that the client then transforms to an `init_mode`.

**Comment by MartijnPieterse** [comment]
I'll try and implement this. When i have a draft implementation i'll edit this message for review.

**Comment by Askaholic** [comment]
Closing this through #635.

We'll need to make changes at some point, when the game_type is saved in the database, but we can make a separate issue for that.
