### ISSUE TITLE
Suggestion: Make the lowest displayed rating = 0

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/server#627]
If you reach a negative rating early on in faf it becomes very difficult to get into another game.

**Comment by Askaholic** [comment]
Maybe this needs to be a client issue. The server is not responsible for the displayed rating, only for the underlying trueskill rating.

**Comment by JaggedAppliance** [comment]
Ok I'll make another issue on the client page. I'll let you decide to close this or not.
