### ISSUE TITLE
Refactor game validity checks

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#636]
When I added the coop validity checks initially, I added them all on the base `Game` class with a switch that checked the featured mod. However in hindsight, I should have made use of the existing object oriented design and put the coop checks in the `CoopGame` subclass. This would have the added benefit of decoupling the coop validity checks from the featured mod. We should also do a similar refactor for the "faf validity checks" as well.

Related code:
https://github.com/FAForever/server/blob/e4ca993a9b7ea8123c64f6917bf9edd05f69b0ce/server/games/game.py#L587

**Comment by 46bit** [comment]
@Askaholic Hey. I had a look into this one and want to check the approach I'm thinking of.

The default `Game.game_mode` is `FeaturedModType.FAF`. But https://github.com/FAForever/server/blob/e4ca993/server/game_service.py#L155 instantiates a `CustomGame` for that game mode. As far as I can tell, `Game` isn't an abstract class but may as well be.

The logic in `validate_game_settings` is shared for all game modes, so it doesn't make sense to duplicate that. I think we're better off adding a `validate_game_mode_settings` method:
* The existing logic in `Game._validate_coop_game_settings` would move to `CoopGame.validate_game_mode_settings`.
* The existing logic in `Game._validate_faf_game_settings` would move to `Game.validate_game_mode_settings` or `CustomGame.validate_game_mode_settings`.

Remaining question is whether `Game` can practically be made abstract or not. Do you have any feelings on that?

**Comment by Askaholic** [comment]
Yea that sounds like what I had in mind, checks that happen for all games (like for unrated maps or mods etc) should happen on the base class, and checks that are specific to some other type of game like a coop game or a ladder game should happen on those classes. Right now there is a direct mapping between featured mod and game class, but that's going to change with TMM. 

With the addition of TMM, we are going to (eventually) get rid of the `ladder1v1` featured mod altogether, and just use the `faf` featured mod, but we will still use the `LadderGame` class for handling the matchmaker specific game logic. And there are also plans to generalize the logic regarding coop, so that we can more easily support coop games that are played using other featured mods, like nomads coop for example.
