### ISSUE TITLE
Show ban duration to user with higher resolution

### ISSUE THREAD

**Issue by Viba** [FAForever/server#639]
Currently users might get ban duration shown as "1 day" when the duration is e.g. 44 hours. It would be better for the users if they'd see at least the days + hours.

I believe this could be done simply by changing the naturaldelta [here ](https://github.com/FAForever/server/blob/ecb4fd7e570a4ceaeb2fe1c34b3302f80b5b565f/server/lobbyconnection.py#L1092)to more precise and cut it to min hours or minutes or something?

**Comment by Askaholic** [comment]
Yea, TBH the server shouldn't be doing localization at all but changing that is a pain because it requires someone to change it on the client side and the client guys don't seem to care.

**Comment by Brutus5000** [comment]
Sarcasm: yes improving user experience for people who break the rules is super important.

**Comment by Viba** [comment]
Yeah I thought about that too, but this change would also mean less queries from users to moderators "when is my ban ending???" :)
