### ISSUE TITLE
Rethink/remove current "smurf-prevention"

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#64]
Short description: It's too much pain for the gain.

Long description:

* Smurfs are not preventable, except players have to identify themselves personally (webcam, passport, etc) against trustful admin
* Therefore, all currently implemented protections are ineffective
* Since FAF is open source, it's easy as pie to circumvent the protection

You may argue that it at least prevents totally unskilled (in terms of programming) people from smurfing - and I agree. But is it worth the effort just to prevent 10 out of 20 smurfs?

Is smurfing really a problem that needs to be solved? If so, the only way to do that is having people identify themselves before they can play ladder, or before they can play at all. Effective, but not very user-friendly.

**Comment by micheljung** [comment]
Alright i saw this is a duplicate of [#2](https://github.com/FAForever/client/issues/2) on client side

**Comment by visionik** [comment]
I don't see this as a duplicate.   I'm strongly opposed to removing smurf protection.   The current system works pretty well, and from an administration standpoint, is absolutely necessary.

In short, I don't see the pain; and speaking empirically instead of theoretically the gain is very real.

**Comment by micheljung** [comment]
ok :-)
