### ISSUE TITLE
Phantom games report results in a different format

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#663]
Right now the result reporting assumes that results always have the form `string number`, which is correct for vanilla games. However, as it turns out, the phantom mod also sends an additional string indicating whether or not the player was a phantom. Maybe it would be worth rewriting the game result processing to handle this format as well. At the very least it would make the scores be saved in the database for phantom games.

```
WARNING  Sep 05  03:10:18 GameConnection                 Invalid result for 5 reported: innocent defeat -3
WARNING  Sep 05  03:17:05 GameConnection                 Invalid result for 3 reported: phantom defeat -1
```

Source code:
https://github.com/FAForever/server/blob/ccf349e3b4bbaee95373d79a0e2f4ee9c5d064a2/server/gameconnection.py#L292-L296

**Comment by ahsanbagwan** [comment]
I would like to take this up.
