### ISSUE TITLE
Remove python client version check

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/server#676]
I would like to drop the table `version_lobby` in the database. The whole version check is sort of pointless today. The database records point to the download of the java client and the minimum version is 0.13.0 which is like 5 years old. Seems like it's completely useless.

Both clients have an auto-update mechanism outside of the faf-database.

Related code (didn't check for tests):
https://github.com/FAForever/server/blob/2932f863432ff2e9ff0d33d203be2f24546c8aee/server/player_service.py#L40
https://github.com/FAForever/server/blob/2932f863432ff2e9ff0d33d203be2f24546c8aee/server/player_service.py#L259-L265
https://github.com/FAForever/server/blob/2932f863432ff2e9ff0d33d203be2f24546c8aee/server/lobbyconnection.py#L458-L478

**Comment by andrewmiko** [comment]
I can work on this issue during #hacktoberfest. Is this about remove code which is somehow related to `self.client_version_info` and table `version_lobby`?

I've found 1 test here:
https://github.com/FAForever/server/blob/9495de5ea09bbcb15f4092567de23f4573a24e31/tests/unit_tests/test_player_service.py#L122

Should this line be removed from test too?

Thanks.

**Comment by Askaholic** [comment]
Yea that’s right. We don’t need to be keeping track of client version numbers at all, so we can just remove any reference to that attribute. You can also run the tests and see what fails after you remove stuff (use the Travis build if you don’t want to set it up locally). Removing this code will also let us get rid of the `semver` dependency (need to update Pipfile and Pipfile.lock)

**Comment by andrewmiko** [comment]
@Askaholic thanks. I will work on it.
