### ISSUE TITLE
TMM: Too many players in the party

### ISSUE THREAD

**Issue by Cheyans** [FAForever/server#719]
See FAForever/downlords-faf-client#2137 for details.

It looks like the issue for a party while the party queuing has been fixed here, I assume it hasn't been released yet #691.

I'd like to open the discussion of allowing more players to join a party than the max number of players allowed for a TMM mode.
I'll reiterate what I mentioned in the ticket above.

I understand this feature may grow into 3v3, 4v4 TMM, etc. But in my opinion it should only allow for party sizes up to the max amount of players on a single team as it doesn't provide any benefit to the players and it just makes it more confusing for them.

**Comment by Askaholic** [comment]
I don't really see a reason to restrict party sizes. If you put too many people in a party, then you can't queue. I think that's fine, and restricting it to some arbitrarily chosen number is just going to hinder us in the future when we have a use case for that.
