### ISSUE TITLE
Czar unit blueprint is wrong

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#735]
It should be `UAA0310` according to [unitdb.faforever.com](https://unitdb.faforever.com). This is causing the czar achievement not to work. Maybe someone can go through and audit all the unit blueprints to make sure we have the right constants in there.

I think the prefixes map like this:
- UE - UEF
- UR - Cybran
- UA - Aeon
- XS - Seraphim

**Comment by MrRowey** [comment]
- Fixed Czar Wrong BP Listed
- Moved Salvation under Experimental field ( was move to Experimental tab Years ago)
