### ISSUE TITLE
Remove references to equilibrium

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#744]
Equilibrium was removed as a featured mod since it stopped being developed. We should remove all hardcoded references to it, there aren't very many.

We should also refactor this:
https://github.com/FAForever/server/blob/4a39a48966bf81fb1617506575de2e4eaa50d399/server/game_service.py#L158-L165

I think it would be best to get rid of the automatic game class detection and pass in the desired class when creating a game.

**Comment by IanNaughton** [comment]
Howdy, I'd like to lend a hand with this issue

**Comment by Askaholic** [comment]
Hi, sounds great! Are you up for taking a stab at removing the game class detection from that function too?

**Comment by IanNaughton** [comment]
Isn't the class detection needed to support the create game calls from the lobbyconnection class (command_game_host function)? If the game class detection is removed from the create_game function, it looks like it would just move up the call stack to command_game_host. Am I understanding that correctly?

**Comment by Askaholic** [comment]
Yep that’s correct, but there just needs to be one case for coop games. Everything else that’s created through `game_host` should be a custom game.

There has been some discussion about supporting coop games using different featured mods e.g. nomads, in which case we would need a different way of deciding when to use the `CoopGame` class. That’s why I think it’s better to make that decision in `game_host` as the game service may not have enough information to be able to decide what is correct. For now we’ll keep checking the featured mod.
