### ISSUE TITLE
Save additional metadata in game results

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#747]
# Motivation
There are some use cases in modded games where the game results may be more nuanced than simply `victory`, `defeat`, or `draw`. For example in phantom games, the results will also include whether or not the player was a phantom. See #663.

For galactic war an army may become defeated by recalling, and it is important that a distinction can be made between a recall defeat and an acu death, as gw includes perma death.

Therefore it would be nice if we could save additional metadata with game result reports and include it in the post game rabbitmq messages. We should just extend the current format similar to how phantomx has already done it by parsing game results as a space-separated list of values where the last value is an integer score and the second to last value is either `defeat`, `victory` or `draw` indicating the result for rating purposes.

# Format specification 
Pseudo-ebnf:
```
{<text> }defeat|victory|draw <integer>
```
Where `<text>` is some lowercase ascii text without whitespace and `<integer>` is an ascii representation of an integer.

Regex:
```regex
([a-z0-9]+ )*(defeat|victory|draw) -?[0-9]+
```

# Handling
The server should not do any special handling of metadata, however it should pass the metadata along in post-game rabbitmq messages so that other services may be able to implement special handling for certain meta tags.

**Comment by eoinnoble** [comment]
You can assign this one to me.
