### ISSUE TITLE
Coop leaderboard was not completely fixed

### ISSUE THREAD

**Issue by Melanol** [FAForever/server#759]
So, I noticed that coop leaderboard is working again, but it doesn't save results every run. I recently beat Operation Trident on around 25 mins, and it didn't save the result. 1 player, everything on default but speed (adjustable). Also, I think that there is no point in keeping multiple records of same players. It should be max 1 per player in 1-player mode, max 1 per 2-player combination.

**Comment by Askaholic** [comment]
Can you post the replay ID?

**Comment by Melanol** [comment]
> Can you post the replay ID?

https://replay.faforever.com/14210327

**Comment by Melanol** [comment]
OK, I guess I had 1 SIM mod on: resource rich. I didn't turn it on myself, but I probably got it turned on when I entered someone else's game.

**Comment by Askaholic** [comment]
Ah ok. That would do it.
