### ISSUE TITLE
Add broadcasted info updates to RabbitMQ

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#771]
There are currently 3 types of messages sent to every client as a broadcasted state update:

- player_info
- game_info
- matchmaker_info

This is handled here: 
https://github.com/FAForever/server/blob/aa535a92b676525f67223be8035fb132ca106f60/server/__init__.py#L141-L142

We should post these updates to a RabbitMQ exchange so that other services can subscribe to them as well. Additionally each `ServerContext` should get a boolean attribute signaling whether it will broadcast updates or not. This would allow us to keep backwards compatible behavior while also handling broadcasts differently for newer clients that support it.

### Use cases
1. Lobby bridge
The lobby bridge idea is to break out some of the network handling into a separate more performant application. This application would proxy connections to the lobby server and would handle the broadcasting of updates. This is desirable because the update broadcasts are very slow in python and are the number 1 cause of CPU load for the lobby server.
2. Galactic War backend
I guess the gw-backend server might want to subscribe to game information.
3. API endpoint
Maybe this could replace or reduce queries to the control server currently used by the API for displaying number of online players and number of active games on the website.

**Comment by Brutus5000** [comment]
4. Do achievement updates over messages rather OAuth / HTTP
