### ISSUE TITLE
Command invalid when db is down

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/server#800]
When the database is down and someone tries to login the error message from the server for why it fails claims that the command is invalid rather than saying the server can't reach the db.

It would probably be good to change this just for debugging purposes

**Comment by KaukaHan** [comment]
nowdays without the database the devserver crashes.

**Comment by Askaholic** [comment]
You'd probably have to start the devserver while the database is up and then take the database down to reproduce this.

**Comment by benjamin-lawson** [comment]
@Askaholic Could you review [my PR](https://github.com/FAForever/server/pull/1009) when you get the chance? All actions are passing including the unit test that I added.
