### ISSUE TITLE
Send game options in `game_launch` message for matchmaker games

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#824]
As we expand the capabilities of the team matchmaker we will need the ability to configure game options from the server. For example in larger matchmaker games (3v3, 4v4+) we may want to disable fullshare (which is currently hardcoded to always be enabled because we wanted it for 2v2).

We should add a new game launch option called `game_options` that is a dictionary mapping option names to values. For example:
```json
{
    "command": "game_launch",
    "game_options": {
        "Share": "FullShare",
        "Victory": "demoralization"
    },
    ...
}
```

Ideally we would pull these from the queue definition in the database, but for now it might be OK to hardcode them in based on team size.

The game launch options are defined here:
https://github.com/FAForever/server/blob/716717f330bf1945e4e1ca2e5e9678257985b9ad/server/types.py#L22-L30
And they are set here:
https://github.com/FAForever/server/blob/716717f330bf1945e4e1ca2e5e9678257985b9ad/server/ladder_service.py#L437-L440

**Comment by BlackYps** [comment]
Hardcoding them based on team size is not a good option, because we probably want to have two different 4v4 queues, one with fullshare and one without.
