### ISSUE TITLE
Make database access not block the event loop

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#84]
Currently, all database access that uses the QSql namespace classes block the entire eventloop (Both with and without using the `asyncio` module).

 - Use aiomysql in:
   - [ ] Game
   - [ ] GameConnection
   - [ ] LobbyConnection
 - [ ] Port the rest of the server to asyncio so it can gain these improvements too

**Comment by micheljung** [comment]
Done?

**Comment by Sheeo** [comment]
Donue and done, yes.
