### ISSUE TITLE
Adjust global rating with ranked matchmaker games

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#845]
Now that we're adding a number of different matchmakers, we want to make it so that new players can use the matchmaker to establish a global rating for themselves. To do this, we want to apply rating changes from the matchmaker back to global, but only if the rating changes are positive (to prevent rating manipulation and other issues).

The way it would work is:
<details>
<summary>Proposal 1</summary>
Whenever a game is rated and the rating used is not global and not hidden, then compute the normalized adjustment made by trueskill to the rating i.e. `(after_mean - before_mean) / before_mean` and `(after_dev - before_dev) / before_dev)`. If the new displayed rating is higher than the displayed global rating, compute the adjusted global rating by applying the normalized changes to the global rating, scaled by the global rating i.e. `global_mean += global_mean * normalized_mean_change` and `global_dev += global_dev * normalized_dev_change`. If the displayed adjusted global rating is higher than the displayed old global rating, save the rating adjustments, otherwise leave the global rating unchanged.

### Example 1
Suppose a player's global rating and matchmaker ratings are both `(1500, 500)` and they **LOSE** a matchmaker game where their new rating returned by trueskill is `(1400, 400)`. Since the new displayed rating `(1400 - 3 * 400) = 200` is higher than the displayed global rating `(1500 - 3 * 500) = 0`, we perform the adjustment as follows: 
- Normalized mean change is `(1400 - 1500) / 1500 = -0.067`
- Normalized deviation change is `(400 - 500) / 500 = -0.200`. 
- Global mean adjustment is `1500 * -0.067 = -100`
- Global deviation adjustment is  `500 * -0.200 = -100`

The adjusted global mean is then computed to be `(1500 - 100, 500 - 100) = (1400, 400)` which is displayed as `200`. Since this is higher than the original displayed global rating `0`, the global rating adjustments are saved.

### Example 2
Suppose a player's global rating is `(1000, 150)` and their matchmaker rating is `(1200, 100)` and they **WIN** a matchmaker game where their new rating returned by trueskill is `(1205, 95)`. Since the new displayed rating `(1205- 3 * 95) = 920` is higher than the displayed global rating `(1000 - 3 * 150) = 550`, we perform the adjustment as follows: 
- Normalized mean change is `(1205 - 1200) / 1200 = 0.0042`
- Normalized deviation change is `(95 - 100) / 100 = -0.0500`. 
- Global mean adjustment is `1000 * 0.0042 = 4.2`
- Global deviation adjustment is  `150 * -0.0500 = -7.500`

The adjusted global mean is then computed to be `(1000 + 4.2, 150 - 7.500) = (1004.2, 142.500)` which is displayed as `567.2`. Since this is higher than the original displayed global rating `550`, the global rating adjustments are saved.

### Example 3
Suppose a player's global rating is `(1000, 150)` and their matchmaker rating is `(1200, 100)` and they **LOSE** a matchmaker game where their new rating returned by trueskill is `(1195, 105)`. Since the new displayed rating `(1195 - 3 * 105) = 880` is higher than the displayed global rating `(1000 - 3 * 150) = 550`, we perform the adjustment as follows: 
- Normalized mean change is `(1195 - 1200) / 1200 = -0.0042`
- Normalized deviation change is `(105 - 100) / 100 = 0.0500`. 
- Global mean adjustment is `1000 *- 0.0042 = -4.2`
- Global deviation adjustment is  `150 * 0.0500 = 7.500`

The adjusted global mean is then computed to be `(1000 - 4.2, 150 + 7.500) = (995.8, 157.500)` which is displayed as `523.3`. Since this is lower than the original displayed global rating `550`, the global rating adjustments are discarded.
</details>

<details>
<summary>Proposal 2</summary>
Whenever a game is rated and the rating used is not global and not hidden, then compute the adjusted global mean by replacing the player's non-global rating with the global mean in the call to the trueskill rating adjustments.

### Scenario 1
Suppose a player's global rating and matchmaker ratings are the same, then the new global rating will exactly equal the matchmaker rating, as the call to trueskill is unchanged.

### Scenario 2 (1vs1)
- MM Rating: `(800, 150)` displayed `350`
- Global rating: `(1000, 150)` displayed `550`
- MM Opponent Rating: `(800, 150)` displayed `350`

Player **WINS**:
- New MM rating: `(848.918, 143.182)` displayed `419`
- New Global rating: `(1031.924, 144.475)` displayed `598`

Player **LOSES**:
- New MM rating: `(751.082, 143.182)` displayed `322`
- New Global rating: `(931.189, 142.189)` displayed `505`
</details>

**Comment by FtXCommando** [comment]
No, the normalization is thrown out if the adjustment caused a decrease in the shown global rating in the after period. My example does not: 9037 > 0.

**Comment by FtXCommando** [comment]
Ok no I'm confusing myself now, it would be (1,500 + 10,500, 500 - 12.5) or (12,000, 487.5) which is 10,537.5 which doesn't get discarded as it's greater than 0.

**Comment by Sheikah45** [comment]
The check if the new displayed rating is higher is not the before and after of global it is the after of the ladder and the before of global. 

`If the new displayed rating is higher than the displayed global rating, compute the adjusted global rating`

So in your example since -545 is less than zero nothing is changed in global according to proposal 1.
