### ISSUE TITLE
Game title additional constraints

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#859]
We should probably be stripping white space off the ends and enforcing a minimum length for the game title.

Also see: https://github.com/FAForever/downlords-faf-client/issues/2420

**Comment by KaukaHan** [comment]
wouldnt it be better to implement this in the client ?

**Comment by Sheikah45** [comment]
Validation of the values should always be done server side as there is no way to guarantee that we will only receive valid values from any client.

**Comment by Askaholic** [comment]
Yea we have to do it on both. The client can do it on a user friendly way that provides instant and localized feedback, but the server is the only place where we can actually guarantee that the rules are followed since there are many different client versions out there, and people can always use one that doesn’t have the checks.
