### ISSUE TITLE
Temporary matchmaker bans for players who fail to connect to games

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#870]
With 4v4 matchmaker we actually need this as a very large number of games don't start. This is often caused by one person, who will likely continue to queue and break games for other people.

- The 'timeouts' or 'bans' need to live across player refafs, but don't need to be saved in the database (in memory is fine)
- Use a progressive system: The first violation results in no penalty, the second results in a short ban, the third and any more thereafter results in a long ban. Once a certain amount of time has gone by with no violations, the count is reset.

**Comment by BlackYps** [comment]
We could also ban the people if they report a defeat result in the first minute of the game. There is basically no way that a game ends legitimately so quickly (only exception is a mutual draw, we should double check that).

**Comment by BlackYps** [comment]
If we ban people for quitting, we should probably tell them in the ban message that they can use mutual draws if they don't like the map instead of just quitting.

**Comment by Sheikah45** [comment]
Can we tell who was at fault for the disconnect? Or would it be the case that if someone loses connection to everyone and a disconnect happens that everyone gets penalized?

**Comment by Askaholic** [comment]
We can sort of tell yes. At the very least we can tell who did not connect to the host.

**Comment by Askaholic** [comment]
This feature was added in #885
