### ISSUE TITLE
Game is rated, even with live observers

### ISSUE THREAD

**Issue by richi235** [FAForever/server#888]
**Describe the bug**
When the host sets "Allow Observers" to yes and more then 0 live observers exist (that can watch both teams) the game is still rated.

Is this intended? I think it is a bug.

**To Reproduce**
Host a game, set "Allow Observers" to yes, play, check for rating changes after game.

**Log or error message**
I'm currently on my notebook, will provide later when I'm on PC again.

**Expected behavior**
No rating changes after games with live observers.

**OS**
We were all on Windows

**Wanna have the bug fixed quickly?**
Depends I think it's kinda important for a competitive community, but it depends on how much this is abused currently

**Comment by richi235** [comment]
cool, thank you.

I think this made games unranked a few months before but I'm not 100% sure either

**Comment by Askaholic** [comment]
This has never unranked games
