### ISSUE TITLE
Perform client time sync on login

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#889]
We would like to send absolute times (ISO timestamps) instead of timedeltas, however, it turns out that a significant number of people have their system time configured incorrectly for whatever reason, which makes the computed deltas show up incorrectly on the client. To mitigate this we should send the current time to the client on login. The client can then compute the difference between this timestamp and the system time and adjust all future timestamps sent by the server using this offset. This should even help to adjust for client latency to the server assuming that the latency is relatively stable.

- Add `current_time` to the command `welcome` sent to the client on login.

**Comment by Askaholic** [comment]
I'm not sure that's really necessary. Drift over a few days shouldn't be noticeable, and if they're going around messing with their system time manually, shouldn't the client be able to handle that on its own?

**Comment by Sheikah45** [comment]
If the change their system time then the client couldn't readjust unless it got another message from the server with what the time is. Otherwise it has no reference point because it can't know how the time has changed as it doesn't get notifications of when the system time is changed externally.

**Comment by KaukaHan** [comment]
Coudn't the client use 'Network Time Protocol' to sync time with any ntp server ?

**Comment by KaukaHan** [comment]
Coudn't the client use 'Network Time Protocol' to sync time with any ntp server ?

**Comment by baterflyrity** [comment]
> The client can then compute the difference between this timestamp and the system time and adjust all future timestamps sent by the server using this offset. This should even help to adjust for client latency to the server assuming that the latency is relatively stable.

Notice this method will work only with several assumptions:
* latency is 0
* jitter is 0
* client time cant jump

all of which are wrong is real life.
