### ISSUE TITLE
Infinite login waiting on wrong username case

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#90]

**Comment by Brute51** [comment]
I can log in with username "Brute51" but I can't with username "brute51" (first char upper case iso lower case). When I do try to log in with the latter FAF does not display a "bad password", which I would expect. Instead it shows a progress bar indefinately. The workaround is to kill the FAF process in the task manager and retry logging in on FAF.

**Comment by Sheeo** [comment]
Fixed on dev
