### ISSUE TITLE
Leaderboard avatars not updating right

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#94]
Chat excerpt:

    dukedickinsson:
    no golden shiny avatar for me then xD, oh well its not like i'm gonna stay in the T2 league for much longer :3
    Sheeo:
    You didn't get the proper league avatar dukedickinsson?
    dukedickinsson:
    in the leaderboards it shows me as the first of my division and first of the T2 league, yet i only get the " third of league avatar "

**Comment by VoRGoR** [comment]
Yes, this has been bugged for >1 year. I've mentioned it before but forgot to make an issue.

**Comment by Sheeo** [comment]
These are going away with the ladder update for now.
