### ISSUE TITLE
Teamkill reporting through GPGNet

### ISSUE THREAD

**Issue by Sheeo** [FAForever/server#95]

**Comment by micheljung** [comment]
Would you mind to elaborate on what needs to be done?

**Comment by Brutus5000** [comment]
1. Create new table for teamkills, I suggest Teamkiller|Victim|Killdate (don't know if you have special name-rules for columns oder table-names)
2. Parse the new GPGNet-command in gameconnection.py in handle_action -->
Add a new case for command == 'Teamkill': Insert parameters from command into database as mentioned above.
Open for disussion: Check how many teamkills were reported for this user and perform additional action? (email to mods or something?)

Btw. quark036 has the perfect client-template to also tackle https://github.com/FAForever/server/issues/109

Would like to work on it but I am unable to run games on my server, so I can't test any code. Will need sheeos advise on this.

**Comment by Sheeo** [comment]
@Brutus5000 catch me in slack any time and we'll get you able to run games, or set you up on the test server.

**Comment by Brutus5000** [comment]
Implemented with the last merge. Will go live with next update tomorrow.
This issue can be closed.
