### ISSUE TITLE
Possibility to create own ban list

### ISSUE THREAD

**Issue by burner-** [FAForever/server#956]
It would be good to have possibility to create own banlist for own hosted games. Currently most who host lot of games keep their own banlist at separated sheet. There is chronical toxic players and chronical laggers what I dont want to own hosted games. So it would be good to have feature what allows add player to banlist. Global banlist would have too big riski to abuse but each host should be freedom to choose do they want take toxic or lagger player to game second time.

**Comment by Sheikah45** [comment]
This is already what the for list does. Any players that you have foed will not see any games you host.

**Comment by Askaholic** [comment]
As Sheikah said, you should add those players to your list of foes. They will no longer be able to join your games.
